### ISSUE TITLE
Playbook Not Found

### ISSUE THREAD

**Issue by sasikanta-fid** [SpringerPE/concourse-ansible-resource#7]
Hi
I am trying use this resource type to execute my ansible playbook but always getting can not find playbook error.Is there any specific folder structure need to be followed?

Traceback (most recent call last):
  File "/opt/resource/out", line 449, in <module>
    rcode = r.run(os.path.basename(__file__))
  File "/opt/resource/resource.py", line 146, in run
    rcode, response = self.update(self.workfolder, source, params)
  File "/opt/resource/out", line 436, in update
    config = self.configure(folder, source, params)
  File "/opt/resource/out", line 389, in configure
    raise ValueError(msg)
ValueError: Cannot find playbook file '/tmp/build/put/ansible-playbook/site.yml'

Thanks
Sasikanta

**Comment by jriguera** [comment]
Yep, its here: https://github.com/SpringerPE/concourse-ansible-resource#ansible-playbook-repo-structure

BTW, the ansible version is quite outdated, be aware of that.
